### ISSUE TITLE
Conflict with Dockerhub personal access tokens and 2FA auth

### ISSUE THREAD

**Issue by mathbunnyru** [christian-korneck/update-container-description-action#1]
Please, could you check if this limitation is still valid?
It is so sad, that it's impossible to use PAT and 2FA simultaneously.

**Comment by mathbunnyru** [comment]
This seems to work now! 🎉 

https://github.com/jupyter/docker-stacks/actions/runs/3368273187/jobs/5586628459

**Comment by mathbunnyru** [comment]
Reopened this as a reminder to change (or maybe remove) https://github.com/christian-korneck/update-container-description-action#limitations

@christian-korneck could you take a look please?

**Comment by christian-korneck** [comment]
good catch, thanks. Done.
